cache:
   npm: false
language: node_js
node_js:
   - '8'
   - '10'
   - "lts/*"                # Active LTS release
   - "node"                 # Latest stable release
after_success:
    - make report-coverage
